---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-ksk-employees
  namespace: fruits
  labels:
    app: restapi-ksk-employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-ksk-employees
  template:
    metadata:
      labels:
        app: restapi-ksk-employees
    spec:
      containers:
      - name: restapi-ksk-employees
        image: 847322629192.dkr.ecr.ap-northeast-2.amazonaws.com/api-backend-dualcidr:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 30002
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-ksk-employees
  namespace: fruits
spec:
  selector:
    app: restapi-ksk-employees
  type: ClusterIP
  ports:
    - name: http
      port: 30002
      protocol: TCP
      targetPort: 30002
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: restapi-ksk-employees-pub-ingress
  namespace: fruits
  labels:
    app: restapi-ksk-employees
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app-bff.pub.tbiz-atcl.net
    http:
      paths:
      - path: /api/ksk
        backend:
          serviceName: restapi-ksk-employees
          servicePort: 30002
